### ISSUE TITLE
Sampling frequency

### ISSUE THREAD

**Issue by gustavovso** [nh2/hemokit#10]
Hi
I run  'hemokit-dump --format spaced' on windows and put the data on a text file, but I don't know if the sampling frequency is 2048Hz or 128Hz. Which frequency is the right one?

**Comment by mdtdev** [comment]
If hemokit can speed up the Emotiv by a factor of 10, I need to get in on this!

The EPOC uses a 1024 Hz sampling rate internally, and then downsamples the data to 128 Hz to return over the wireless connection. So, with no real knowledge of hemokit, I'd assume that it returns at the usual hardware rate of 128 Hz.

**Comment by nh2** [comment]
Yes, 128 Hz, see also https://github.com/nh2/hemokit/blob/b2d78925eca1ed992d9fe43ba50057065c8b8fec/src/Hemokit.hs#L88.

Please reopen if you need more info!
