### ISSUE TITLE
No devices found

### ISSUE THREAD

**Issue by basophobic** [nh2/hemokit#11]
Hello,
I have installed hemokit latest version along with hidapi (@chpatrick) with no errorrs on a Linux Ubuntu 16.04 LTS system, but when I try to execute hemokit-dump (or any other programs), it results with the following error:
> hemokit-dump: user error (No devices found.)

I have also installed separately on the same machine emokit (@qdot) and my Emotiv Epoc headset is being recognized both using the python scripts, and the executables files. The VID and PID of the headset are inserted in the rules file accordingly (in /etc/udev/rules.d), and the device is recognized under /dev/hidraw1 and 2 (lsusb command also shows the headset correctly).
Any hints? I have obviously not looked everywhere, so any help would be appreciated.
Thanks in advance

**Comment by basophobic** [comment]
Coming back to this, I just compiled hidapi using the testgui option. All work well when hidapi-hidraw-testgui runs. Emotiv is seen and can be connected and data come from the electrodes. So it must be something wrong I'm doing on the hemokit side.

**Comment by nh2** [comment]
When scanning for devices, Hemokit uses the IDs known to me at the time I wrote them:

https://github.com/nh2/hemokit/blob/b2d78925eca1ed992d9fe43ba50057065c8b8fec/src/Hemokit.hs#L380

https://github.com/nh2/hemokit/blob/b2d78925eca1ed992d9fe43ba50057065c8b8fec/src/Hemokit.hs#L322

If your vendor or device ID are different, you'll beable to use `hemokit-dump` giving the device explicitly, but not the automatic detection.

**Comment by nh2** [comment]
This should be fixed with commit https://github.com/nh2/hemokit/commit/3ca11ae836218f0109eb5b5215c5c1033827de47

**Comment by basophobic** [comment]
Problem solved! All works as expected! Thanks a lot!
