### ISSUE TITLE
Installation Failure

### ISSUE THREAD

**Issue by jaydevnarayan** [nh2/hemokit#2]
I tried installing the hemokit-dump.exe but the execution file is not running.... Pls help me...

**Comment by nh2** [comment]
What do you mean by "installing"? Which Windows version? Are you running it from the command line?

**Comment by nh2** [comment]
Ping :)

**Comment by jaydevnarayan** [comment]
Hey Niklas....
Sorry for being late....
Im facing trouble in connecting the Hemokit to openvibe acquisition
server.....
I followed the steps given in Github... Still failed to sort this out...
Do advice me...

Regards
Venki :)

**Comment by jaydevnarayan** [comment]
Im using windows7 Home basic...and i'm not running it from the command
line.... :(

**Comment by nh2** [comment]
> Do advice me...

To help you I need to know *exactly* what the problem is :)

> and i'm not running it from the command line

I think you should really run `hemokit.exe` from the Windows command line.

**Comment by jaydevnarayan** [comment]
ok....i'm running it from the command window now.
I entered the command
 hemokit-dump --format sensorbytes --serve 127.0.0.1:1337
then it returns the following statement in the command window

option --format: Format is not valid. Must be 'default','json', or 'spaced'.
Usage: hemokit-dump [--model MODEL] [--serial SERIALNUMBER] [--from-file
PATH] [--mode ARG] [--realtime] [--list] [--format ARG] [--serve HOST:PORT]

**Comment by warrenarea** [comment]
can you try the command again  jaydevnarayan
are you sure you didnt accidentally do --format Format 
as that is what it appears like.

i've tried that exact command you posted and it works fine for me.

**Comment by warrenarea** [comment]
also ensure you have the latest builds: 
https://github.com/nh2/hemokit/releases

**Comment by jaydevnarayan** [comment]
I entered the command in a different computer and it worked just fine. I
cant understand what actually is the problem with my system :(

**Comment by warrenarea** [comment]
are you still having a problem with this issue jaydevnarayan or can we close this issue?

**Comment by nh2** [comment]
Closing for now - feel free to reopen if the problem is still there.
